"""Side-by-side excerpts: the same detection, every model's report (Section 6.8).

A table of groundedness scores says which model is more faithful. It does not
show a reader what an unfaithful report looks like. This writes, for a few
chosen detections, the evidence the models were given followed by each model's
report in full, with its scores -- quoted exactly, so the report can lift them.

**Which detections.** Chosen by rule, not by eye, so the excerpts cannot be
cherry-picked to flatter a model:

1. the detection where groundedness differs most between models;
2. the false-positive detection (a benign flow the detector flagged) where it
   differs most -- the study's sharpest arm;
3. the genuinely ambiguous detection where it differs most.

Ties, and the case where every model scores alike, fall back to pack order. The
rule used for each excerpt is printed above it. `--detection-id` overrides.

Usage:
    python scripts/export_llm_excerpts.py
    python scripts/export_llm_excerpts.py --prompt-version v2 -n 5
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from gnnids.llm.prompts import render_facts  # noqa: E402

REPORTS = REPO_ROOT / "results" / "reports"


def load_runs(version: str, reports_dir: Path = REPORTS) -> list[dict]:
    runs = []
    for f in sorted(reports_dir.glob("reports_*.json")):
        d = json.loads(f.read_text())
        if d.get("prompt_version") == version and not d.get("smoke"):
            runs.append(d)
    return runs


def spread(runs: list[dict], detection_id: str) -> float:
    """Range of groundedness across models for one detection (0 if < 2 scores)."""
    vals = []
    for run in runs:
        row = next((r for r in run["reports"] if r["detection_id"] == detection_id), None)
        g = (row or {}).get("scores", {}).get("groundedness")
        if isinstance(g, (int, float)):
            vals.append(g)
    return max(vals) - min(vals) if len(vals) > 1 else 0.0


def choose(runs: list[dict], n: int) -> list[tuple[str, str]]:
    """(detection id, the rule that selected it), at most `n`, no repeats."""
    common = None
    for run in runs:
        ids = [r["detection_id"] for r in run["reports"]]
        common = ids if common is None else [i for i in common if i in set(ids)]
    common = common or []
    first = {r["detection_id"]: r for r in runs[0]["reports"]} if runs else {}

    def best(pool: list[str]) -> str | None:
        # max() keeps the first of equal spreads, i.e. pack order.
        return max(pool, key=lambda i: spread(runs, i)) if pool else None

    rules = [
        ("largest difference in groundedness between models", common),
        ("false positive (a benign flow the detector flagged) with the largest "
         "difference", [i for i in common if first[i].get("true_label") == "Benign"]),
        ("ambiguous detection with the largest difference",
         [i for i in common if first[i].get("uncertainty")]),
    ]
    picked: list[tuple[str, str]] = []
    for rule, pool in rules:
        pool = [i for i in pool if i not in {p[0] for p in picked}]
        pick = best(pool)
        if pick:
            if spread(runs, pick) == 0:
                # Say so, rather than let a heading claim a difference that the
                # scores do not show.
                rule += " — no difference between models here, so the first in pack order"
            picked.append((pick, rule))
    for i in common:                       # fill up in pack order
        if len(picked) >= n:
            break
        if i not in {p[0] for p in picked}:
            picked.append((i, "next in pack order"))
    return picked[:n]


def render(runs: list[dict], packs: dict[str, dict], picks: list[tuple[str, str]],
           version: str) -> str:
    out = [f"# Side-by-side reports — prompt {version}", "",
           "Generated by `scripts/export_llm_excerpts.py`. Report text is quoted "
           "exactly as each model produced it. Detections are selected by rule; "
           "the rule is stated above each.", ""]
    for n, (det, rule) in enumerate(picks, 1):
        pack = packs.get(det)
        out += [f"## Excerpt {n} — {rule}", "", f"Detection `{det}`", ""]
        if pack:
            out += [f"True label: **{pack['flow'].get('true_label')}** · "
                    f"detector's category: **{pack['detection']['predicted_class']}** "
                    f"(confidence {pack['detection']['class_confidence']})", "",
                    "**Evidence given to every model:**", "", render_facts(pack), ""]
        for run in runs:
            row = next((r for r in run["reports"] if r["detection_id"] == det), None)
            out += [f"### {run['provider']} / {run['model']}", ""]
            if row is None or not row.get("ok"):
                out += [f"*No report: {(row or {}).get('error') or 'not generated'}*", ""]
                continue
            s = row.get("scores", {})
            cls, att = row.get("classification") or {}, row.get("attribution") or {}
            out += [
                f"groundedness **{s.get('groundedness')}** · "
                f"fabricated addresses {len(s.get('fabricated_addresses', []))} · "
                f"names the predicted category: {cls.get('names_predicted', 'n/a')} · "
                f"attributed features cited: {att.get('coverage', 'n/a')} · "
                f"{s.get('report_words')} words", ""]
            ungrounded = [e for k in s.get("per_class", {}).values()
                          for e in k.get("ungrounded", [])]
            if ungrounded:
                out += [f"Not in the evidence: `{'`, `'.join(ungrounded)}`", ""]
            out += ["> " + line for line in row["report"].strip().splitlines()]
            out += [""]
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--prompt-version", default="v1")
    ap.add_argument("-n", type=int, default=3, help="number of excerpts")
    ap.add_argument("--detection-id", nargs="+", default=None)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    runs = load_runs(args.prompt_version)
    if not runs:
        raise SystemExit(f"no reports for prompt {args.prompt_version} in {REPORTS}")
    packs_path = REPO_ROOT / "results" / "evidence" / runs[0]["packs_source"]
    packs = ({p["detection_id"]: p for p in json.loads(packs_path.read_text())}
             if packs_path.exists() else {})
    picks = ([(d, "chosen by hand (--detection-id)") for d in args.detection_id]
             if args.detection_id else choose(runs, args.n))

    out = args.out or REPORTS / f"excerpts_{args.prompt_version}.md"
    out.write_text(render(runs, packs, picks, args.prompt_version))
    print(f"{len(picks)} excerpt(s) across {len(runs)} model(s):")
    for det, rule in picks:
        print(f"  {det[:8]}  {rule}")
    shown = out.relative_to(REPO_ROOT) if out.is_relative_to(REPO_ROOT) else out
    print(f"\nwritten -> {shown}\n")


if __name__ == "__main__":
    main()
